# Global settings
title: Valerie Merchant
author: Valerie Merchant
email: me@vmerch.me
description: "Designer & Wiener Lover"
url: "vmerch.github.io"
markdown: kramdown

markdown:       kramdown
highlighter:    pygments
permalink:      pretty
encoding:       UTF-8

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
  - vendor
  - bower.json

sass:
  sass_dir: _sass
  style: compressed
